version: "3.9"
services:
  telephonedirectorydb:
   image: mongo
   networks:
    - dev 
  rabbitmq:
   image: rabbitmq:3.12.5-management
   networks:
    - dev 
networks:
   dev:
volumes:
  telephonedirectorydb_volume: