version: "3.9"
services:
  telephonedirectorydb:
   container_name: telephonedirectorydb
   restart: always
   ports:
        - "27017:27017"
   volumes:
     - telephonedirectorydb_volume:/data/db
  rabbitmq:
   container_name: rabbitmq
   restart: always
   ports: 
        - 127.0.0.1:5672:5672
        - 127.0.0.1:15672:15672